-- INSERT INTO kart_parts (id, name, part_type, img_link) VALUES
--     (1001, 'Standard Kart', BODY, 'https://mario.wiki.gallery/images/thumb/0/05/StandardKartBodyMK8.png/180px-StandardKartBodyMK8.png'),
--     (1001, 'Standard Kart', BODY, 'https://mario.wiki.gallery/images/thumb/0/05/StandardKartBodyMK8.png/180px-StandardKartBodyMK8.png'),
--     (1002, 'Pipe Frame', 'BODY', 'https://mario.wiki.gallery/images/thumb/d/d1/PipeFrameBodyMK8.png/180px-PipeFrameBodyMK8.png'),
--     (1003, 'Mach8', 'BODY', 'https://mario.wiki.gallery/images/thumb/d/df/Mach8BodyMK8.png/180px-Mach8BodyMK8.png'),
--     (1004, 'Steel Driver', 'BODY', 'https://mario.wiki.gallery/images/thumb/9/94/Steel_Driver.png/180px-Steel_Driver.png'),
--     (1005, 'Cat Cruiser', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/f4/CatCruiserBodyMK8.png/180px-CatCruiserBodyMK8.png'),
--     (1006, 'Circuit Special', 'BODY', 'https://mario.wiki.gallery/images/thumb/6/6c/CircuitSpecialBodyMK8.png/180px-CircuitSpecialBodyMK8.png'),
--     (1007, 'Tri-Speeder', 'BODY', 'https://mario.wiki.gallery/images/thumb/5/56/TrispeederBodyMK8.png/180px-TrispeederBodyMK8.png'),
--     (1008, 'Bandwagon', 'BODY', 'https://mario.wiki.gallery/images/thumb/c/c2/BadwagonBodyMK8.png/180px-BadwagonBodyMK8.png'),
--     (1009, 'Prancer', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/ff/PrancerBodyMK8.png/180px-PrancerBodyMK8.png'),
--     (1010, 'Buggybud', 'BODY', 'https://mario.wiki.gallery/images/thumb/4/45/BiddybuggyBodyMK8.png/180px-BiddybuggyBodyMK8.png'),
--     (1011, 'Landship', 'BODY', 'https://mario.wiki.gallery/images/thumb/6/6d/LandshipBodyMK8.png/180px-LandshipBodyMK8.png'),
--     (1012, 'Sneeker', 'BODY', 'https://mario.wiki.gallery/images/thumb/4/47/SneakerBodyMK8.png/180px-SneakerBodyMK8.png'),
--     (1013, 'Sports Coupe', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/f8/SportsCoupeMK8.png/180px-SportsCoupeMK8.png'),
--     (1014, 'Gold Standard', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/fe/Gold_Standard.png/180px-Gold_Standard.png'),
--     (1015, 'GLA', 'BODY', 'https://mario.wiki.gallery/images/thumb/c/c2/GLA-MK8.png/180px-GLA-MK8.png'),
--     (1016, 'W 25 Silver Arrow', 'BODY', 'https://mario.wiki.gallery/images/thumb/2/25/W25SilverArrow-MK8.png/180px-W25SilverArrow-MK8.png'),
--     (1017, '300 SL Roadster', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/f4/300SLRoadster_MK8.png/180px-300SLRoadster_MK8.png'),
--     (1018, 'Blue Falcon', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/f6/MK8BlueFalcon.png/180px-MK8BlueFalcon.png'),
--     (1019, 'Tanooki Kart', 'BODY', 'https://mario.wiki.gallery/images/thumb/7/76/MK8_Tanooki_Buggy_Sprite.png/180px-MK8_Tanooki_Buggy_Sprite.png'),
--     (1020, 'B Dasher', 'BODY', 'https://mario.wiki.gallery/images/thumb/1/15/ZeldaMK8Bdasher.png/180px-ZeldaMK8Bdasher.png'),
--     (1021, 'Streetle', 'BODY', 'https://mario.wiki.gallery/images/thumb/c/cf/MK8Streetle.png/180px-MK8Streetle.png'),
--     (1022, 'P-Wing', 'BODY', 'https://mario.wiki.gallery/images/thumb/c/cd/MK8PWing.png/180px-MK8PWing.png'),
--     (1023, 'Koopa Clown', 'BODY', 'https://mario.wiki.gallery/images/thumb/7/70/MK8DX_Koopa_Clown.png/180px-MK8DX_Koopa_Clown.png'),
--     (1024, 'Standard Bike', 'BODY', 'https://mario.wiki.gallery/images/thumb/8/84/StandardBikeBodyMK8.png/180px-StandardBikeBodyMK8.png'),
--     (1025, 'The Duke', 'BODY', 'https://mario.wiki.gallery/images/thumb/8/8a/TheDukeBodyMK8.png/180px-TheDukeBodyMK8.png'),
--     (1026, 'Flame Rider', 'BODY', 'https://mario.wiki.gallery/images/thumb/3/31/FlameRiderBodyMK8.png/180px-FlameRiderBodyMK8.png'),
--     (1027, 'Varmint', 'BODY', 'https://mario.wiki.gallery/images/thumb/d/d0/VarmintBodyMK8.png/180px-VarmintBodyMK8.png'),
--     (1028, 'Mr. Scooty', 'BODY', 'https://mario.wiki.gallery/images/thumb/1/18/MrScootyBodyMK8.png/180px-MrScootyBodyMK8.png'),
--     (1029, 'Master Cycle Zero', 'BODY', 'https://mario.wiki.gallery/images/thumb/2/26/MK8D_Master_Cycle_Zero.png/180px-MK8D_Master_Cycle_Zero.png'),
--     (1030, 'City Tripper', 'BODY', 'https://mario.wiki.gallery/images/thumb/b/be/MK8_Light-Green_City_Tripper.png/180px-MK8_Light-Green_City_Tripper.png'),
--     (1031, 'Comet', 'BODY', 'https://mario.wiki.gallery/images/thumb/0/0e/CometBodyMK8.png/180px-CometBodyMK8.png'),
--     (1032, 'Sport Bike', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/fe/SportBikeBodyMK8.png/180px-SportBikeBodyMK8.png'),
--     (1033, 'Jet Bike', 'BODY', 'https://mario.wiki.gallery/images/thumb/1/12/JetBikeBodyMK8.png/180px-JetBikeBodyMK8.png'),
--     (1034, 'Yoshi Bike', 'BODY', 'https://mario.wiki.gallery/images/thumb/6/62/YoshiBikeBodyMK8.png/180px-YoshiBikeBodyMK8.png'),
--     (1035, 'Master Cycle', 'BODY', 'https://mario.wiki.gallery/images/thumb/8/8a/MK8MasterCycle.png/180px-MK8MasterCycle.png'),
--     (1036, 'Standard ATV', 'BODY', 'https://mario.wiki.gallery/images/thumb/2/23/StandardATVBodyMK8.png/180px-StandardATVBodyMK8.png'),
--     (1037, 'Wild Wiggler', 'BODY', 'https://mario.wiki.gallery/images/thumb/a/aa/WildWigglerBodyMK8.png/180px-WildWigglerBodyMK8.png'),,
--     (1038, 'Teddy Buggy', 'BODY', 'https://mario.wiki.gallery/images/thumb/f/fa/TeddyBuggyBodyMK8.png/180px-TeddyBuggyBodyMK8.png'),
--     (1039, 'Bone Rattler', 'BODY', 'https://mario.wiki.gallery/images/thumb/0/0a/MK8BoneRattler.png/180px-MK8BoneRattler.png'),
--     (1040, 'Splat Buggy', 'BODY', 'https://mario.wiki.gallery/images/thumb/6/63/MK8DX_Splat_Buggy.png/180px-MK8DX_Splat_Buggy.png'),
--     (1041, 'Inkstriker', 'BODY', 'https://mario.wiki.gallery/images/thumb/e/eb/MK8DX_Inkstriker.png/180px-MK8DX_Inkstriker.png'),
--     (1042, 'Standard', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/a/a8/StandardTiresMK8.png/180px-StandardTiresMK8.png'),
--     (1043, 'Monster', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/2/29/MonsterTiresMK8.png/180px-MonsterTiresMK8.png'),
--     (1044, 'Roller', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/7/76/RollerTiresMK8.png/180px-RollerTiresMK8.png'),
--     (1045, 'Slim', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/f/f8/SlimTiresMK8.png/180px-SlimTiresMK8.png'),
--     (1046, 'Slick', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/d/dd/SlickTiresMK8.png/180px-SlickTiresMK8.png'),
--     (1047, 'Metal', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/9/96/MetalTiresMK8.png/180px-MetalTiresMK8.png'),
--     (1048, 'Button', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/0/07/ButtonTiresMK8.png/180px-ButtonTiresMK8.png'),
--     (1049, 'Off-Road', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/2/25/Off-Road.png/180px-Off-Road.png'),
--     (1050, 'Sponge', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/4/4c/SpongeTiresMK8.png/180px-SpongeTiresMK8.png'),
--     (1051, 'Wood', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/0/03/WoodTiresMK8.png/180px-WoodTiresMK8.png'),
--     (1052, 'Cushion', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/9/92/CushionTiresMK8.png/180px-CushionTiresMK8.png'),
--     (1053, 'Blue Standard', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/d/db/Blue_Standard.png/180px-Blue_Standard.png'),
--     (1054, 'Funky Monster', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/d/d1/HotMonsterTiresMK8.png/180px-HotMonsterTiresMK8.png'),
--     (1055, 'Azure Roller', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/f/fe/AzureRollerTiresMK8.png/180px-AzureRollerTiresMK8.png'),
--     (1056, 'Crimson Slim', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/7/71/CrimsonSlimTiresMK8.png/180px-CrimsonSlimTiresMK8.png'),
--     (1057, 'Cyber Slick', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/2/29/CyberSlickTiresMK8.png/180px-CyberSlickTiresMK8.png'),
--     (1058, 'Retro  Off-road', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/4/48/Retro_Off-Road.png/180px-Retro_Off-Road.png'),
--     (1059, 'Gold Tires', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/5/52/Gold_Tires_MK8.png/180px-Gold_Tires_MK8.png'),
--     (1060, 'GLA Tires', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/b/ba/GLATires-MK8.png/180px-GLATires-MK8.png'),
--     (1061, 'Triforce Tires', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/9/9d/MK8-TriforceTires.png/180px-MK8-TriforceTires.png'),
--     (1062, 'Ancient Tires', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/d/d5/MK8D_Ancient_Tires.png/180px-MK8D_Ancient_Tires.png'),
--     (1063, 'Leaf Tires', 'WHEELS', 'https://mario.wiki.gallery/images/thumb/f/f9/Leaf_Tires_MK8.png/180px-Leaf_Tires_MK8.png'),
--     (1064, 'Super Glider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/a/a8/SuperGliderMK8.png/180px-SuperGliderMK8.png'),
--     (1065, 'Cloud Glider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/8/84/Cloud_Glider.png/180px-Cloud_Glider.png'),
--     (1066, 'Wario Wing', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/a/ae/WarioWingMK8.png/180px-WarioWingMK8.png'),
--     (1067, 'Waddle Wing', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/e/ef/WaddleWingMK8.png/180px-WaddleWingMK8.png'),
--     (1068, 'Peach Parasol', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/6/6e/PeachParasolGliderMK8.png/180px-PeachParasolGliderMK8.png'),
--     (1069, 'Parachute', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/d/dd/ParachuteGliderMK8.png/180px-ParachuteGliderMK8.png'),
--     (1070, 'Parafoil', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/c/c4/ParafoilGliderMK8.png/180px-ParafoilGliderMK8.png'),
--     (1071, 'Flower Glider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/b/b3/FlowerGliderMK8.png/180px-FlowerGliderMK8.png'),
--     (1072, 'Bowser Kite', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/f/f7/BowserKiteMK8.png/180px-BowserKiteMK8.png'),
--     (1073, 'Plane Glider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/c/ca/PlaneGliderMK8.png/180px-PlaneGliderMK8.png'),
--     (1074, 'MKTV Parafoil', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/9/96/MKTVParafoilGliderMK8.png/180px-MKTVParafoilGliderMK8.png'),
--     (1075, 'Gold Glider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/1/18/GoldGliderMK8.png/180px-GoldGliderMK8.png'),
--     (1076, 'Hylian Kite', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/9/9c/MK8-HylianKite.png/180px-MK8-HylianKite.png'),
--     (1077, 'Paraglider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/3/39/MK8D_Paraglider.png/180px-MK8D_Paraglider.png'),
--     (1078, 'Paper Glider', 'GLIDER', 'https://mario.wiki.gallery/images/thumb/0/0e/PaperGliderIcon-MK8.png/180px-PaperGliderIcon-MK8.png');
--

INSERT INTO Characters (id, name, img_link) VALUES (1001, 'Mario', 'https://mario.wiki.gallery/images/thumb/d/d9/MK8_Mario_Icon.png/96px-MK8_Mario_Icon.png'),
    (1002, 'Luigi', 'https://mario.wiki.gallery/images/thumb/5/51/MK8_Luigi_Icon.png/96px-MK8_Luigi_Icon.png'),
    (1003, 'Peach', 'https://mario.wiki.gallery/images/thumb/c/c2/MK8_Peach_Icon.png/96px-MK8_Peach_Icon.png'),
    (1004, 'Daisy', 'https://mario.wiki.gallery/images/thumb/3/32/MK8_Daisy_Icon.png/96px-MK8_Daisy_Icon.png'),
    (1005, 'Rosalina', 'https://mario.wiki.gallery/images/thumb/8/89/MK8_Rosalina_Icon.png/96px-MK8_Rosalina_Icon.png'),
    (1006, 'Tanooki Mario', 'https://mario.wiki.gallery/images/thumb/a/a2/MK8_Tanooki_Mario_Icon.png/96px-MK8_Tanooki_Mario_Icon.png'),
    (1007, 'Cat Peach', 'https://mario.wiki.gallery/images/thumb/a/ad/MK8_Cat_Peach_Icon.png/96px-MK8_Cat_Peach_Icon.png'),
    (1008, 'Birdo', 'https://mario.wiki.gallery/images/thumb/f/f6/MK8D_Birdo_Icon.png/96px-MK8D_Birdo_Icon.png'),
    (1009, 'Yoshi', 'https://mario.wiki.gallery/images/thumb/9/91/MK8_Yoshi_Icon.png/96px-MK8_Yoshi_Icon.png'),
    (1010, 'Toad', 'https://mario.wiki.gallery/images/thumb/4/45/MK8_Toad_Icon.png/96px-MK8_Toad_Icon.png'),
    (1011, 'Koopa Troopa', 'https://mario.wiki.gallery/images/thumb/b/bc/MK8_Koopa_Icon.png/96px-MK8_Koopa_Icon.png'),
    (1012, 'Shy Guy', 'https://mario.wiki.gallery/images/thumb/7/7f/MK8_ShyGuy_Icon.png/96px-MK8_ShyGuy_Icon.png'),
    (1013, 'Lakitu', 'https://mario.wiki.gallery/images/thumb/7/7d/MK8_Lakitu_Icon.png/96px-MK8_Lakitu_Icon.png'),
    (1014, 'Toadette', 'https://mario.wiki.gallery/images/thumb/8/8e/MK8_Toadette_Icon.png/96px-MK8_Toadette_Icon.png'),
    (1015, 'King Boo', 'https://mario.wiki.gallery/images/thumb/1/1d/MK8DX_King_Boo_Icon.png/96px-MK8DX_King_Boo_Icon.png'),
    (1016, 'Petey Piranha', 'https://mario.wiki.gallery/images/thumb/8/86/MK8DX_Petey_Piranha_Icon.png/96px-MK8DX_Petey_Piranha_Icon.png'),
    (1017, 'Baby Mario', 'https://mario.wiki.gallery/images/thumb/d/d2/MK8_BabyMario_Icon.png/96px-MK8_BabyMario_Icon.png'),
    (1018, 'Baby Luigi', 'https://mario.wiki.gallery/images/thumb/a/aa/MK8_BabyLuigi_Icon.png/96px-MK8_BabyLuigi_Icon.png'),
    (1019, 'Baby Peach', 'https://mario.wiki.gallery/images/thumb/3/3d/MK8_BabyPeach_Icon.png/96px-MK8_BabyPeach_Icon.png'),
    (1020, 'Baby Daisy', 'https://mario.wiki.gallery/images/thumb/4/43/MK8_BabyDaisy_Icon.png/96px-MK8_BabyDaisy_Icon.png'),
    (1021, 'Baby Rosalina', 'https://mario.wiki.gallery/images/thumb/0/09/MK8_BabyRosalina_Icon.png/96px-MK8_BabyRosalina_Icon.png'),
    (1022, 'Metal Mario', 'https://mario.wiki.gallery/images/thumb/e/e3/MK8_MMario_Icon.png/96px-MK8_MMario_Icon.png'),
    (1023, 'Pink Gold Peach', 'https://mario.wiki.gallery/images/thumb/0/0d/MK8_PGPeach_Icon.png/96px-MK8_PGPeach_Icon.png'),
    (1024, 'Wiggler', 'https://mario.wiki.gallery/images/thumb/7/7e/MK8DX_Wiggler_Icon.png/96px-MK8DX_Wiggler_Icon.png'),
    (1025, 'Wario', 'https://mario.wiki.gallery/images/thumb/c/c2/MK8_Wario_Icon.png/96px-MK8_Wario_Icon.png'),
    (1026, 'Waluigi', 'https://mario.wiki.gallery/images/thumb/7/78/MK8_Waluigi_Icon.png/96px-MK8_Waluigi_Icon.png'),
    (1027, 'Donkey Kong', 'https://mario.wiki.gallery/images/thumb/0/08/MK8_DKong_Icon.png/96px-MK8_DKong_Icon.png'),
    (1028, 'Bowser', 'https://mario.wiki.gallery/images/thumb/4/47/MK8_Bowser_Icon.png/96px-MK8_Bowser_Icon.png'),
    (1029, 'Dry Bones', 'https://mario.wiki.gallery/images/thumb/3/3f/MK8DX_Dry_Bones_Icon.png/96px-MK8DX_Dry_Bones_Icon.png'),
    (1030, 'Bowser Jr.', 'https://mario.wiki.gallery/images/thumb/2/26/MK8_Bowser_Jr_Icon.png/96px-MK8_Bowser_Jr_Icon.png'),
    (1031, 'Dry Bowser', 'https://mario.wiki.gallery/images/thumb/2/29/MK8_Dry_Bowser_Icon.png/96px-MK8_Dry_Bowser_Icon.png'),
    (1032, 'Kamek', 'https://mario.wiki.gallery/images/thumb/0/00/MK8DX_Kamek_Icon.png/96px-MK8DX_Kamek_Icon.png'),
    (1033, 'Lemmy', 'https://mario.wiki.gallery/images/thumb/f/fc/MK8_Lemmy_Icon.png/96px-MK8_Lemmy_Icon.png'),
    (1034, 'Larry', 'https://mario.wiki.gallery/images/thumb/c/c2/MK8_Larry_Icon.png/96px-MK8_Larry_Icon.png'),
    (1035, 'Wendy', 'https://mario.wiki.gallery/images/thumb/d/d9/MK8_Wendy_Icon.png/96px-MK8_Wendy_Icon.png'),
    (1036, 'Ludwig', 'https://mario.wiki.gallery/images/thumb/a/a8/MK8_Ludwig_Icon.png/96px-MK8_Ludwig_Icon.png'),
    (1037, 'Iggy', 'https://mario.wiki.gallery/images/thumb/d/dd/MK8_Iggy_Icon.png/96px-MK8_Iggy_Icon.png'),
    (1038, 'Roy', 'https://mario.wiki.gallery/images/thumb/3/3e/MK8_Roy_Icon.png/96px-MK8_Roy_Icon.png'),
    (1039, 'Morton', 'https://mario.wiki.gallery/images/thumb/7/72/MK8_Morton_Icon.png/96px-MK8_Morton_Icon.png'),
    (1040, 'Peachette', 'https://mario.wiki.gallery/images/thumb/f/fd/MK8DX_Peachette_Icon.png/96px-MK8DX_Peachette_Icon.png'),
    (1041, 'Inkling Girl', 'https://mario.wiki.gallery/images/thumb/b/b9/MK8DX_Female_Inkling_Icon.png/96px-MK8DX_Female_Inkling_Icon.png'),
    (1042, 'Villager', 'https://mario.wiki.gallery/images/thumb/1/16/VillagerMale-Icon-MK8.png/96px-VillagerMale-Icon-MK8.png'),
    (1043, 'Isabelle', 'https://mario.wiki.gallery/images/thumb/2/20/MK8_Isabelle_Icon.png/96px-MK8_Isabelle_Icon.png'),
    (1044, 'Link', 'https://mario.wiki.gallery/images/thumb/9/9e/MK8D_BotW_Link_Icon.png/96px-MK8D_BotW_Link_Icon.png'),
    (1045, 'Diddy Kong', 'https://mario.wiki.gallery/images/thumb/8/82/MK8DX_Diddy_Kong_Icon.png/96px-MK8DX_Diddy_Kong_Icon.png'),
    (1046, 'Funky Kong', 'https://mario.wiki.gallery/images/thumb/4/4a/MK8DX_Funky_Kong_Icon.png/96px-MK8DX_Funky_Kong_Icon.png'),
    (1047, 'Pauline', 'https://mario.wiki.gallery/images/thumb/d/dd/MK8DX_Pauline_Icon.png/96px-MK8DX_Pauline_Icon.png'),
    (1048, 'Mii', 'https://mario.wiki.gallery/images/thumb/b/bb/Mii_MK8.png/96px-Mii_MK8.png');

INSERT INTO courses (id, name, img_link) VALUES (1001, 'Mario Kart Stadium', 'https://mario.wiki.gallery/images/thumb/0/09/MK8_Mario_Kart_Stadium_Course_Icon.png/228px-MK8_Mario_Kart_Stadium_Course_Icon.png'),
    (1002, 'Water Park', 'https://mario.wiki.gallery/images/thumb/4/40/MK8_Water_Park_Course_Icon.png/228px-MK8_Water_Park_Course_Icon.png'),
    (1003, 'Sweet Sweet Canyon', 'https://mario.wiki.gallery/images/thumb/a/ad/MK8_Sweet_Sweet_Canyon_Course_Icon.png/228px-MK8_Sweet_Sweet_Canyon_Course_Icon.png'),
    (1004, 'Thwomp Ruins', 'https://mario.wiki.gallery/images/thumb/e/e8/MK8_Thwomp_Ruins_Course_Icon.png/228px-MK8_Thwomp_Ruins_Course_Icon.png'),
    (1005, 'Mario Circuit', 'https://mario.wiki.gallery/images/thumb/2/28/MK8_Mario_Circuit_Course_Icon.png/228px-MK8_Mario_Circuit_Course_Icon.png'),
    (1006, 'Toad Harbor', 'https://mario.wiki.gallery/images/thumb/2/2a/MK8_Toad_Harbor_Course_Icon.png/228px-MK8_Toad_Harbor_Course_Icon.png'),
    (1007, 'Twisted Mansion', 'https://mario.wiki.gallery/images/thumb/6/68/MK8_Twisted_Mansion_Course_Icon.png/228px-MK8_Twisted_Mansion_Course_Icon.png'),
    (1008, 'Shy Guy Falls', 'https://mario.wiki.gallery/images/thumb/2/2a/MK8_Shy_Guy_Falls_Course_Icon.png/228px-MK8_Shy_Guy_Falls_Course_Icon.png'),
    (1009, 'Sunshine Airport', 'https://mario.wiki.gallery/images/thumb/9/99/MK8_Sunshine_Airport_Course_Icon.png/228px-MK8_Sunshine_Airport_Course_Icon.png'),
    (1010, 'Dolphin Shoals', 'https://mario.wiki.gallery/images/thumb/f/fc/MK8_Dolphin_Shoals_Course_Icon.png/228px-MK8_Dolphin_Shoals_Course_Icon.png'),
    (1011, 'Electrodome', 'https://mario.wiki.gallery/images/thumb/1/14/MK8_Electrodrome_Course_Icon.png/228px-MK8_Electrodrome_Course_Icon.png'),
    (1012, 'Mount Wario', 'https://mario.wiki.gallery/images/thumb/3/38/MK8_Mount_Wario_Course_Icon.png/228px-MK8_Mount_Wario_Course_Icon.png'),
    (1013, 'Cloudtop Cruise', 'https://mario.wiki.gallery/images/thumb/8/81/MK8_Cloudtop_Cruise_Course_Icon.png/228px-MK8_Cloudtop_Cruise_Course_Icon.png'),
    (1014, 'Bone-Dry Dunes', 'https://mario.wiki.gallery/images/thumb/d/d3/MK8_Bone-Dry_Dunes_Course_Icon.png/228px-MK8_Bone-Dry_Dunes_Course_Icon.png'),
    (1015, 'Bowsers Castle', 'https://mario.wiki.gallery/images/thumb/2/2b/MK8_Bowser%27s_Castle_Course_Icon.png/228px-MK8_Bowser%27s_Castle_Course_Icon.png'),
    (1016, 'Rainbow Road', 'https://mario.wiki.gallery/images/thumb/7/77/MK8_Rainbow_Road_Course_Icon.png/228px-MK8_Rainbow_Road_Course_Icon.png'),
    (1017, 'Yoshi Circuit', 'https://mario.wiki.gallery/images/thumb/9/94/MK8_GCN_Yoshi_Circuit_Course_Icon.png/228px-MK8_GCN_Yoshi_Circuit_Course_Icon.png'),
    (1018, 'Excitebike Arena', 'https://mario.wiki.gallery/images/thumb/5/57/MK8_Excitebike_Arena_Course_Icon.png/228px-MK8_Excitebike_Arena_Course_Icon.png'),
    (1019, 'Dragon Driftway', 'https://mario.wiki.gallery/images/thumb/b/bb/MK8_Dragon_Driftway_Course_Icon.png/228px-MK8_Dragon_Driftway_Course_Icon.png'),
    (1020, 'Mute City', 'https://mario.wiki.gallery/images/thumb/f/fa/MK8_Mute_City_Course_Icon.png/228px-MK8_Mute_City_Course_Icon.png'),
    (1021, 'Baby Park', 'https://mario.wiki.gallery/images/thumb/3/34/MK8_GCN_Baby_Park_Course_Icon.png/228px-MK8_GCN_Baby_Park_Course_Icon.png'),
    (1022, 'Cheese Land', 'https://mario.wiki.gallery/images/thumb/1/15/MK8_GBA_Cheese_Land_Course_Icon.png/228px-MK8_GBA_Cheese_Land_Course_Icon.png'),
    (1023, 'Wild Woods', 'https://mario.wiki.gallery/images/thumb/e/e4/MK8_Wild_Woods_Course_Icon.png/228px-MK8_Wild_Woods_Course_Icon.png'),
    (1024, 'Animal Crossing', 'https://mario.wiki.gallery/images/thumb/1/15/MK8_Animal_Crossing_Course_Icon.png/228px-MK8_Animal_Crossing_Course_Icon.png'),
    (1025, 'Wii Moo Moo Meadows', 'https://mario.wiki.gallery/images/thumb/9/97/MK8_Wii_Moo_Moo_Meadows_Course_Icon.png/228px-MK8_Wii_Moo_Moo_Meadows_Course_Icon.png'),
    (1026, 'GBA Mario Circuit', 'https://mario.wiki.gallery/images/thumb/f/f7/MK8_GBA_Mario_Circuit_Course_Icon.png/228px-MK8_GBA_Mario_Circuit_Course_Icon.png'),
    (1027, 'DS Cheep Cheep Beach', 'https://mario.wiki.gallery/images/thumb/9/9e/MK8_DS_Cheep_Cheep_Beach_Course_Icon.png/228px-MK8_DS_Cheep_Cheep_Beach_Course_Icon.png'),
    (1028, 'N64 Toads Turnpike', 'https://mario.wiki.gallery/images/thumb/5/55/MK8_N64_Toad%27s_Turnpike_Course_Icon.png/228px-MK8_N64_Toad%27s_Turnpike_Course_Icon.png'),
    (1029, 'GCN Dry Dry Desert', 'https://mario.wiki.gallery/images/thumb/6/64/MK8_GCN_Dry_Dry_Desert_Course_Icon.png/228px-MK8_GCN_Dry_Dry_Desert_Course_Icon.png'),
    (1030, 'SNES Donut Plains 3', 'https://mario.wiki.gallery/images/thumb/b/b1/MK8_SNES_Donut_Plains_3_Course_Icon.png/228px-MK8_SNES_Donut_Plains_3_Course_Icon.png'),
    (1031, 'N64 Royal Raceway', 'https://mario.wiki.gallery/images/thumb/8/8a/MK8_N64_Royal_Raceway_Course_Icon.png/228px-MK8_N64_Royal_Raceway_Course_Icon.png'),
    (1032, '3DS DK Jungle', 'https://mario.wiki.gallery/images/thumb/3/35/MK8_3DS_DK_Jungle_Course_Icon.png/228px-MK8_3DS_DK_Jungle_Course_Icon.png'),
    (1033, 'DS Wario Stadium', 'https://mario.wiki.gallery/images/thumb/1/1a/MK8_DS_Wario_Stadium_Course_Icon.png/228px-MK8_DS_Wario_Stadium_Course_Icon.png'),
    (1034, 'GCN Sherbet Land', 'https://mario.wiki.gallery/images/thumb/3/3f/MK8_GCN_Sherbet_Land_Course_Icon.png/228px-MK8_GCN_Sherbet_Land_Course_Icon.png'),
    (1035, '3DS Music Park', 'https://mario.wiki.gallery/images/thumb/9/94/MK8_3DS_Music_Park_Course_Icon.png/228px-MK8_3DS_Music_Park_Course_Icon.png'),
    (1036, 'N64 Yoshi Valley', 'https://mario.wiki.gallery/images/thumb/a/a4/MK8_N64_Yoshi_Valley_Course_Icon.png/228px-MK8_N64_Yoshi_Valley_Course_Icon.png'),
    (1037, 'DS Tick-Tock Clock', 'https://mario.wiki.gallery/images/thumb/0/0b/MK8_DS_Tick-Tock_Clock_Course_Icon.png/228px-MK8_DS_Tick-Tock_Clock_Course_Icon.png'),
    (1038, '3DS Piranha Plant Slide', 'https://mario.wiki.gallery/images/thumb/d/d1/MK8_3DS_Piranha_Plant_Slide_Course_Icon.png/228px-MK8_3DS_Piranha_Plant_Slide_Course_Icon.png'),
    (1039, 'Wii Grumble Volcano', 'https://mario.wiki.gallery/images/thumb/b/b2/MK8_Wii_Grumble_Volcano_Course_Icon.png/228px-MK8_Wii_Grumble_Volcano_Course_Icon.png'),
    (1040, 'N64 Rainbow Road', 'https://mario.wiki.gallery/images/thumb/b/b9/MK8_N64_Rainbow_Road_Course_Icon.png/228px-MK8_N64_Rainbow_Road_Course_Icon.png'),
    (1041, 'Wii Warios Gold Mine', 'https://mario.wiki.gallery/images/thumb/9/94/MK8_Wii_Wario%27s_Gold_Mine_Course_Icon.png/228px-MK8_Wii_Wario%27s_Gold_Mine_Course_Icon.png'),
    (1042, 'SNES Rainbow Road', 'https://mario.wiki.gallery/images/thumb/0/05/MK8_SNES_Rainbow_Road_Course_Icon.png/228px-MK8_SNES_Rainbow_Road_Course_Icon.png'),
    (1043, 'Ice Ice Outpost', 'https://mario.wiki.gallery/images/thumb/c/c4/MK8_Ice_Ice_Outpost_Course_Icon.png/228px-MK8_Ice_Ice_Outpost_Course_Icon.png'),
    (1044, 'Hyrule Circuit', 'https://mario.wiki.gallery/images/thumb/5/5e/MK8_Hyrule_Circuit_Course_Icon.png/228px-MK8_Hyrule_Circuit_Course_Icon.png'),
    (1045, '3DS Neo Bowser City', 'https://mario.wiki.gallery/images/thumb/b/b0/MK8_3DS_Neo_Bowser_City_Course_Icon.png/228px-MK8_3DS_Neo_Bowser_City_Course_Icon.png'),
    (1046, 'GBA Ribbon Road', 'https://mario.wiki.gallery/images/thumb/e/e2/MK8_GBA_Ribbon_Road_Course_Icon.png/228px-MK8_GBA_Ribbon_Road_Course_Icon.png'),
    (1047, 'Super Bell Subway', 'https://mario.wiki.gallery/images/thumb/7/7e/MK8_Super_Bell_Subway_Course_Icon.png/228px-MK8_Super_Bell_Subway_Course_Icon.png'),
    (1048, 'Big Blue', 'https://mario.wiki.gallery/images/thumb/0/06/MK8_Big_Blue_Course_Icon.png/228px-MK8_Big_Blue_Course_Icon.png'),
    (1049, 'Tour Paris Promenade', 'https://mario.wiki.gallery/images/thumb/b/bb/MK8D_Tour_Paris_Promenade_Course_Icon.png/228px-MK8D_Tour_Paris_Promenade_Course_Icon.png'),
    (1050, '3DS Toad Circuit', 'https://mario.wiki.gallery/images/thumb/3/3b/MK8D_3DS_Toad_Circuit_Course_Icon.png/228px-MK8D_3DS_Toad_Circuit_Course_Icon.png'),
    (1051, 'N64 Choco Mountain', 'https://mario.wiki.gallery/images/thumb/7/74/MK8D_N64_Choco_Mountain_Course_Icon.png/228px-MK8D_N64_Choco_Mountain_Course_Icon.png'),
    (1052, 'Wii Coconut Mall', 'https://mario.wiki.gallery/images/thumb/9/98/MK8D_Wii_Coconut_Mall_Course_Icon.png/228px-MK8D_Wii_Coconut_Mall_Course_Icon.png'),
    (1053, 'Tour Tokyo Blur', 'https://mario.wiki.gallery/images/thumb/8/81/MK8D_Tour_Tokyo_Blur_Course_Icon.png/228px-MK8D_Tour_Tokyo_Blur_Course_Icon.png'),
    (1054, 'DS Shroom Ridge', 'https://mario.wiki.gallery/images/thumb/7/7e/MK8D_DS_Shroom_Ridge_Course_Icon.png/228px-MK8D_DS_Shroom_Ridge_Course_Icon.png'),
    (1055, 'GBA Sky Garden', 'https://mario.wiki.gallery/images/thumb/0/09/MK8D_GBA_Sky_Garden_Course_Icon.png/228px-MK8D_GBA_Sky_Garden_Course_Icon.png'),
    (1056, 'Ninja Hideaway', 'https://mario.wiki.gallery/images/thumb/b/b1/MK8D_Ninja_Hideaway_Course_Icon.png/228px-MK8D_Ninja_Hideaway_Course_Icon.png'),
    (1057, 'Tour New York Minute', 'https://mario.wiki.gallery/images/thumb/d/d7/MK8D_Tour_New_York_Minute_Course_Icon.png/228px-MK8D_Tour_New_York_Minute_Course_Icon.png'),
    (1058, 'SNES Mario Circuit', 'https://mario.wiki.gallery/images/thumb/e/e4/MK8D_SNES_Mario_Circuit_3_Course_Icon.png/228px-MK8D_SNES_Mario_Circuit_3_Course_Icon.png'),
    (1059, 'N64 Kalimari Desert', 'https://mario.wiki.gallery/images/thumb/3/3e/MK8D_N64_Kalimari_Desert_Course_Icon.png/228px-MK8D_N64_Kalimari_Desert_Course_Icon.png'),
    (1060, 'DS Waluigi Pinball', 'https://mario.wiki.gallery/images/thumb/b/b6/MK8D_DS_Waluigi_Pinball_Course_Icon.png/228px-MK8D_DS_Waluigi_Pinball_Course_Icon.png'),
    (1061, 'Tour Sydney Sprint', 'https://mario.wiki.gallery/images/thumb/d/d4/MK8D_Tour_Sydney_Sprint_Course_Icon.png/228px-MK8D_Tour_Sydney_Sprint_Course_Icon.png'),
    (1062, 'GBA Snow Land', 'https://mario.wiki.gallery/images/thumb/b/bc/MK8D_GBA_Snow_Land_Course_Icon.png/228px-MK8D_GBA_Snow_Land_Course_Icon.png'),
    (1063, 'Wii Mushroom Gorge', 'https://mario.wiki.gallery/images/thumb/f/fb/MK8D_Wii_Mushroom_Gorge_Course_Icon.png/228px-MK8D_Wii_Mushroom_Gorge_Course_Icon.png'),
    (1064, 'Sky-High Sundae', 'https://mario.wiki.gallery/images/thumb/d/d0/MK8D_Sky-High_Sundae_Course_Icon.png/228px-MK8D_Sky-High_Sundae_Course_Icon.png'),
    (1065, 'Tour London Loop', 'https://mario.wiki.gallery/images/thumb/2/24/MK8D_Tour_London_Loop_Course_Icon.png/228px-MK8D_Tour_London_Loop_Course_Icon.png'),
    (1066, 'GBA Boo Lake', 'https://mario.wiki.gallery/images/thumb/7/71/MK8D_GBA_Boo_Lake_Course_Icon.png/228px-MK8D_GBA_Boo_Lake_Course_Icon.png'),
    (1067, '3DS Rock Rock Mountain', 'https://mario.wiki.gallery/images/thumb/e/ee/MK8D_3DS_Rock_Rock_Mountain_Course_Icon.png/228px-MK8D_3DS_Rock_Rock_Mountain_Course_Icon.png'),
    (1068, 'Wii Maple Treeway', 'https://mario.wiki.gallery/images/thumb/c/c9/MK8D_Wii_Maple_Treeway_Course_Icon.png/228px-MK8D_Wii_Maple_Treeway_Course_Icon.png'),
    (1069, 'Tour Berlin Byways', 'https://mario.wiki.gallery/images/thumb/7/73/MK8D_Tour_Berlin_Byways_Course_Icon.png/228px-MK8D_Tour_Berlin_Byways_Course_Icon.png'),
    (1070, 'DS Peach Gardens', 'https://mario.wiki.gallery/images/thumb/0/0b/MK8D_DS_Peach_Gardens_Course_Icon.png/228px-MK8D_DS_Peach_Gardens_Course_Icon.png'),
    (1071, 'Merry Mountain', 'https://mario.wiki.gallery/images/thumb/5/56/MK8D_Merry_Mountain_Course_Icon.png/228px-MK8D_Merry_Mountain_Course_Icon.png'),
    (1072, '3DS Rainbow Road', 'https://mario.wiki.gallery/images/thumb/9/9f/MK8D_3DS_Rainbow_Road_Course_Icon.png/228px-MK8D_3DS_Rainbow_Road_Course_Icon.png'),
    (1073, 'Tour Amsterdam Drift', 'https://mario.wiki.gallery/images/thumb/c/c1/MK8D_Tour_Amsterdam_Drift_Course_Icon.png/228px-MK8D_Tour_Amsterdam_Drift_Course_Icon.png'),
    (1074, 'GBA Riverside Park', 'https://mario.wiki.gallery/images/thumb/5/5d/MK8D_GBA_Riverside_Park_Course_Icon.png/228px-MK8D_GBA_Riverside_Park_Course_Icon.png'),
    (1075, 'Wii DK Summit', 'https://mario.wiki.gallery/images/thumb/0/01/MK8D_Wii_DK_Summit_Course_Icon.png/228px-MK8D_Wii_DK_Summit_Course_Icon.png'),
    (1076, 'Yoshis Island', 'https://mario.wiki.gallery/images/thumb/2/23/MK8D_Yoshi%27s_Island_Course_Icon.png/228px-MK8D_Yoshi%27s_Island_Course_Icon.png'),
    (1077, 'Tour Bangkok Rush', 'https://mario.wiki.gallery/images/thumb/f/f2/MK8D_Tour_Bangkok_Rush_Course_Icon.png/228px-MK8D_Tour_Bangkok_Rush_Course_Icon.png'),
    (1078, 'DS Mario Circuit', 'https://mario.wiki.gallery/images/thumb/2/2c/MK8D_DS_Mario_Circuit_Course_Icon.png/228px-MK8D_DS_Mario_Circuit_Course_Icon.png'),
    (1079, 'GCN Waluigi Stadium', 'https://mario.wiki.gallery/images/thumb/f/f6/MK8D_GCN_Waluigi_Stadium_Course_Icon.png/228px-MK8D_GCN_Waluigi_Stadium_Course_Icon.png'),
    (1080, 'Tour Singapore Speedway', 'https://mario.wiki.gallery/images/thumb/f/f5/MK8D_Tour_Singapore_Speedway_Course_Icon.png/228px-MK8D_Tour_Singapore_Speedway_Course_Icon.png'),
    (1081, 'Tour Athens Dash', 'https://mario.wiki.gallery/images/thumb/0/0a/MK8D_Tour_Athens_Dash_Course_Icon.png/228px-MK8D_Tour_Athens_Dash_Course_Icon.png'),
    (1082, 'GCN Daisy Cruiser', 'https://mario.wiki.gallery/images/thumb/9/98/MK8D_GCN_Daisy_Cruiser_Course_Icon.png/228px-MK8D_GCN_Daisy_Cruiser_Course_Icon.png'),
    (1083, 'Wii Moonview Highway', 'https://mario.wiki.gallery/images/thumb/7/7c/MK8D_Wii_Moonview_Highway_Course_Icon.png/228px-MK8D_Wii_Moonview_Highway_Course_Icon.png'),
    (1084, 'Squeaky Clean Sprint', 'https://mario.wiki.gallery/images/thumb/a/af/MK8D_Squeaky_Clean_Sprint_Course_Icon.png/228px-MK8D_Squeaky_Clean_Sprint_Course_Icon.png'),
    (1085, 'Tour Los Angeles Laps', 'https://mario.wiki.gallery/images/thumb/2/23/MK8D_Tour_Los_Angeles_Laps_Course_Icon.png/228px-MK8D_Tour_Los_Angeles_Laps_Course_Icon.png'),
    (1086, 'GBA Sunset Wilds', 'https://mario.wiki.gallery/images/thumb/1/11/MK8D_GBA_Sunset_Wilds_Course_Icon.png/228px-MK8D_GBA_Sunset_Wilds_Course_Icon.png'),
    (1087, 'Wii Koopa Cape', 'https://mario.wiki.gallery/images/thumb/5/5a/MK8D_Wii_Koopa_Cape_Course_Icon.png/228px-MK8D_Wii_Koopa_Cape_Course_Icon.png'),
    (1088, 'Tour Vancouver Velocity', 'https://mario.wiki.gallery/images/thumb/6/60/MK8D_Tour_Vancouver_Velocity_Course_Icon.png/228px-MK8D_Tour_Vancouver_Velocity_Course_Icon.png'),
    (1089, 'Tour Rome Avanti', 'https://mario.wiki.gallery/images/thumb/c/c4/MK8D_Tour_Rome_Avanti_Course_Icon.png/228px-MK8D_Tour_Rome_Avanti_Course_Icon.png'),
    (1090, 'GCN DK Mountain', 'https://mario.wiki.gallery/images/thumb/2/28/MK8D_GCN_DK_Mountain_Course_Icon.png/228px-MK8D_GCN_DK_Mountain_Course_Icon.png'),
    (1091, 'Wii Daisy Circuit', 'https://mario.wiki.gallery/images/thumb/c/cf/MK8D_Wii_Daisy_Circuit_Course_Icon.png/228px-MK8D_Wii_Daisy_Circuit_Course_Icon.png'),
    (1092, 'Piranha Plant Cove', 'https://mario.wiki.gallery/images/thumb/c/c3/MK8D_Piranha_Plant_Cove_Course_Icon.png/228px-MK8D_Piranha_Plant_Cove_Course_Icon.png'),
    (1093, 'Tour madrid Drive', 'https://mario.wiki.gallery/images/thumb/4/4f/MK8D_Tour_Madrid_Drive_Course_Icon.png/228px-MK8D_Tour_Madrid_Drive_Course_Icon.png'),
    (1094, '3DS Rosalinas Ice World', 'https://mario.wiki.gallery/images/thumb/1/1d/MK8D_3DS_Rosalina%27s_Ice_World_Course_Icon.png/228px-MK8D_3DS_Rosalina%27s_Ice_World_Course_Icon.png'),
    (1095, 'SNES Bowsers Castle 3', 'https://mario.wiki.gallery/images/thumb/1/1e/MK8D_SNES_Bowser_Castle_3_Course_Icon.png/228px-MK8D_SNES_Bowser_Castle_3_Course_Icon.png'),
    (1096, 'Wii Rainbow Road', 'https://mario.wiki.gallery/images/thumb/0/0c/MK8D_Wii_Rainbow_Road_Course_Icon.png/228px-MK8D_Wii_Rainbow_Road_Course_Icon.png');